//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LineBusPOA.ServiceBusPOA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service/", ConfigurationName="ServiceBusPOA.ServiceBusPOA")]
    public interface ServiceBusPOA {
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/ServiceBusPOA/searchUserNamePassRequest", ReplyAction="http://service/ServiceBusPOA/searchUserNamePassResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LineBusPOA.ServiceBusPOA.searchUserNamePassResponse searchUserNamePass(LineBusPOA.ServiceBusPOA.searchUserNamePassRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/ServiceBusPOA/searchUserNamePassRequest", ReplyAction="http://service/ServiceBusPOA/searchUserNamePassResponse")]
        System.Threading.Tasks.Task<LineBusPOA.ServiceBusPOA.searchUserNamePassResponse> searchUserNamePassAsync(LineBusPOA.ServiceBusPOA.searchUserNamePassRequest request);
        
        // CODEGEN: O parâmetro 'arg0' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/ServiceBusPOA/registerUserRequest", ReplyAction="http://service/ServiceBusPOA/registerUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LineBusPOA.ServiceBusPOA.registerUserResponse registerUser(LineBusPOA.ServiceBusPOA.registerUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/ServiceBusPOA/registerUserRequest", ReplyAction="http://service/ServiceBusPOA/registerUserResponse")]
        System.Threading.Tasks.Task<LineBusPOA.ServiceBusPOA.registerUserResponse> registerUserAsync(LineBusPOA.ServiceBusPOA.registerUserRequest request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/ServiceBusPOA/searchUserRequest", ReplyAction="http://service/ServiceBusPOA/searchUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LineBusPOA.ServiceBusPOA.searchUserResponse searchUser(LineBusPOA.ServiceBusPOA.searchUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/ServiceBusPOA/searchUserRequest", ReplyAction="http://service/ServiceBusPOA/searchUserResponse")]
        System.Threading.Tasks.Task<LineBusPOA.ServiceBusPOA.searchUserResponse> searchUserAsync(LineBusPOA.ServiceBusPOA.searchUserRequest request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/ServiceBusPOA/searchAllRequest", ReplyAction="http://service/ServiceBusPOA/searchAllResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LineBusPOA.ServiceBusPOA.searchAllResponse searchAll(LineBusPOA.ServiceBusPOA.searchAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/ServiceBusPOA/searchAllRequest", ReplyAction="http://service/ServiceBusPOA/searchAllResponse")]
        System.Threading.Tasks.Task<LineBusPOA.ServiceBusPOA.searchAllResponse> searchAllAsync(LineBusPOA.ServiceBusPOA.searchAllRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchUserNamePass", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class searchUserNamePassRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public searchUserNamePassRequest() {
        }
        
        public searchUserNamePassRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchUserNamePassResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class searchUserNamePassResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public searchUserNamePassResponse() {
        }
        
        public searchUserNamePassResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class user : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nomeField;
        
        private string senhaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
                this.RaisePropertyChanged("senha");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class busPOA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string idField;
        
        private string nomeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("nome");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registerUser", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class registerUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LineBusPOA.ServiceBusPOA.user arg0;
        
        public registerUserRequest() {
        }
        
        public registerUserRequest(LineBusPOA.ServiceBusPOA.user arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registerUserResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class registerUserResponse {
        
        public registerUserResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchUser", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class searchUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public searchUserRequest() {
        }
        
        public searchUserRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchUserResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class searchUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public searchUserResponse() {
        }
        
        public searchUserResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchAll", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class searchAllRequest {
        
        public searchAllRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchAllResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class searchAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LineBusPOA.ServiceBusPOA.busPOA[] @return;
        
        public searchAllResponse() {
        }
        
        public searchAllResponse(LineBusPOA.ServiceBusPOA.busPOA[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceBusPOAChannel : LineBusPOA.ServiceBusPOA.ServiceBusPOA, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceBusPOAClient : System.ServiceModel.ClientBase<LineBusPOA.ServiceBusPOA.ServiceBusPOA>, LineBusPOA.ServiceBusPOA.ServiceBusPOA {
        
        public ServiceBusPOAClient() {
        }
        
        public ServiceBusPOAClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceBusPOAClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBusPOAClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBusPOAClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LineBusPOA.ServiceBusPOA.searchUserNamePassResponse LineBusPOA.ServiceBusPOA.ServiceBusPOA.searchUserNamePass(LineBusPOA.ServiceBusPOA.searchUserNamePassRequest request) {
            return base.Channel.searchUserNamePass(request);
        }
        
        public bool searchUserNamePass(string arg0, string arg1) {
            LineBusPOA.ServiceBusPOA.searchUserNamePassRequest inValue = new LineBusPOA.ServiceBusPOA.searchUserNamePassRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            LineBusPOA.ServiceBusPOA.searchUserNamePassResponse retVal = ((LineBusPOA.ServiceBusPOA.ServiceBusPOA)(this)).searchUserNamePass(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LineBusPOA.ServiceBusPOA.searchUserNamePassResponse> LineBusPOA.ServiceBusPOA.ServiceBusPOA.searchUserNamePassAsync(LineBusPOA.ServiceBusPOA.searchUserNamePassRequest request) {
            return base.Channel.searchUserNamePassAsync(request);
        }
        
        public System.Threading.Tasks.Task<LineBusPOA.ServiceBusPOA.searchUserNamePassResponse> searchUserNamePassAsync(string arg0, string arg1) {
            LineBusPOA.ServiceBusPOA.searchUserNamePassRequest inValue = new LineBusPOA.ServiceBusPOA.searchUserNamePassRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((LineBusPOA.ServiceBusPOA.ServiceBusPOA)(this)).searchUserNamePassAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LineBusPOA.ServiceBusPOA.registerUserResponse LineBusPOA.ServiceBusPOA.ServiceBusPOA.registerUser(LineBusPOA.ServiceBusPOA.registerUserRequest request) {
            return base.Channel.registerUser(request);
        }
        
        public void registerUser(LineBusPOA.ServiceBusPOA.user arg0) {
            LineBusPOA.ServiceBusPOA.registerUserRequest inValue = new LineBusPOA.ServiceBusPOA.registerUserRequest();
            inValue.arg0 = arg0;
            LineBusPOA.ServiceBusPOA.registerUserResponse retVal = ((LineBusPOA.ServiceBusPOA.ServiceBusPOA)(this)).registerUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LineBusPOA.ServiceBusPOA.registerUserResponse> LineBusPOA.ServiceBusPOA.ServiceBusPOA.registerUserAsync(LineBusPOA.ServiceBusPOA.registerUserRequest request) {
            return base.Channel.registerUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<LineBusPOA.ServiceBusPOA.registerUserResponse> registerUserAsync(LineBusPOA.ServiceBusPOA.user arg0) {
            LineBusPOA.ServiceBusPOA.registerUserRequest inValue = new LineBusPOA.ServiceBusPOA.registerUserRequest();
            inValue.arg0 = arg0;
            return ((LineBusPOA.ServiceBusPOA.ServiceBusPOA)(this)).registerUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LineBusPOA.ServiceBusPOA.searchUserResponse LineBusPOA.ServiceBusPOA.ServiceBusPOA.searchUser(LineBusPOA.ServiceBusPOA.searchUserRequest request) {
            return base.Channel.searchUser(request);
        }
        
        public bool searchUser(int arg0) {
            LineBusPOA.ServiceBusPOA.searchUserRequest inValue = new LineBusPOA.ServiceBusPOA.searchUserRequest();
            inValue.arg0 = arg0;
            LineBusPOA.ServiceBusPOA.searchUserResponse retVal = ((LineBusPOA.ServiceBusPOA.ServiceBusPOA)(this)).searchUser(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LineBusPOA.ServiceBusPOA.searchUserResponse> LineBusPOA.ServiceBusPOA.ServiceBusPOA.searchUserAsync(LineBusPOA.ServiceBusPOA.searchUserRequest request) {
            return base.Channel.searchUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<LineBusPOA.ServiceBusPOA.searchUserResponse> searchUserAsync(int arg0) {
            LineBusPOA.ServiceBusPOA.searchUserRequest inValue = new LineBusPOA.ServiceBusPOA.searchUserRequest();
            inValue.arg0 = arg0;
            return ((LineBusPOA.ServiceBusPOA.ServiceBusPOA)(this)).searchUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LineBusPOA.ServiceBusPOA.searchAllResponse LineBusPOA.ServiceBusPOA.ServiceBusPOA.searchAll(LineBusPOA.ServiceBusPOA.searchAllRequest request) {
            return base.Channel.searchAll(request);
        }
        
        public LineBusPOA.ServiceBusPOA.busPOA[] searchAll() {
            LineBusPOA.ServiceBusPOA.searchAllRequest inValue = new LineBusPOA.ServiceBusPOA.searchAllRequest();
            LineBusPOA.ServiceBusPOA.searchAllResponse retVal = ((LineBusPOA.ServiceBusPOA.ServiceBusPOA)(this)).searchAll(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LineBusPOA.ServiceBusPOA.searchAllResponse> LineBusPOA.ServiceBusPOA.ServiceBusPOA.searchAllAsync(LineBusPOA.ServiceBusPOA.searchAllRequest request) {
            return base.Channel.searchAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<LineBusPOA.ServiceBusPOA.searchAllResponse> searchAllAsync() {
            LineBusPOA.ServiceBusPOA.searchAllRequest inValue = new LineBusPOA.ServiceBusPOA.searchAllRequest();
            return ((LineBusPOA.ServiceBusPOA.ServiceBusPOA)(this)).searchAllAsync(inValue);
        }
    }
}
